### ISSUE TITLE
[EPIC] Segmentació del públic objectiu de la Newsletter (Newsletter selectiva)

### ISSUE THREAD

**Issue by tramuntanal** [gencat/participa#50]
## Is your feature request related to a problem? Please describe.
Actualment existeix la necessitat de seleccionar l’enviament de newsletters més enllà de si els usuaris es fan seguidors d’un procés participatiu o espai de participació (gamificació). Es vol poder enviar newsletters segons la participació o l’interès dels usuaris.

Related on Decidim/Decidim: https://github.com/decidim/decidim/issues/5028
La idea és ampliar la funcionalitat que ja comença a tenir Decidim de selecció d'interessos:
- [x] Gencat: eliminar temes i convertir-los en scopes. Depends upon: #49 
- [x] Permetre crear newsletters segmentades per participants i per scopes.

## Describe the solution you'd like

Hi haurà dos tipus de segmentació AND: espai participatiu / àmbits. 
Els administradors tenen diferents permisos: SuperAdmin, Admin de Departament, Admin de procés (rol d’usuari d’administració d’un procés). 

### Segmentació per espai participatiu
Es proposa poder segmentar per espai participatiu,
- [x] ParticipatoryProcess
- [x] Assembly
- [x] Conference
- [x] Initiatives
- [x] Consultations

Això suposarà que es podrà discriminar l’enviament de butlletins en funció de l’espai participatiu. Es podrà seleccionar un procés/assemblea/consulta en concret o a tots, en funció dels permisos que tingui l’administrador. 

Per altre banda, es podrà indicar de forma AND si s’envia a Participants (definició de participant decidim) i/o Seguidors (followers del procés/assemblea/etc) dels espais participatius o procés/assemblea/etc.  

### Segmentació per àmbit
Es proposa poder segmentar per àmbit. Actualment, Decidim permet que els usuaris puguin seleccionar els seus interessos, que no deixen de ser els àmbits que la plataforma tingui definits.
Això suposarà que l’admin podrà enviar el butlletí a tots els usuaris interessats en un àmbit en concret.

### Segmentació pel Rol de l’administrador. 

Admin: Visualitza tots els espais de participació. Visualitza els àmbits. Per tant, pot enviar a tota la plataforma o discriminar espai participatiu + interés / espai participatiu / interés. 
AdminDep: Visualitza els processos, assemblees, consultes, etc. assignades al seu Departament. No visualitza els àmbits. Depends upon: https://github.com/gencat/participa/issues/51
AdminProcés: Visualitza els processos, assemblees, consultes, etc. que li han estat assignat directement. No visualitza els àmbits. 
Admin i AdminDep i AdminProcés, tots tres han de poder enviar butlletins.

Així doncs: 
- [x] un Admin podrà seleccionar qualsevol espai participatiu. A cada espai participatiu tindrà la opció de marcar Tots per no anar un per un. 
- [x] un Admin de Departament només podrà seleccionar aquells espais participatius que siguin del seu departament. A cada espai participatiu tindrà la opció de marcar Tots (que fan referència a tots els assignats al seu Departament),
- [x] un Admin de procés (rol d’usuari), només podrà seleccionar aquells processos/assemblees que tingui assignats. A cada espai participatiu tindrà la opció de marcar Tots (que fan referència a tots els assignats al seu usuari),
-  [x] Només l'Admin podrà segmentar per interessos.
- [x] A dins del multiselects, hi ha d’haver la opció a tots. 
- [x] L’administrador ha de seleccionar o bé el checkbox de tots els EspaisParticipatius o bé algún/s en concret. I després esollir Follows o participants (preseleccionts tots dos per defecte, caldrà validar que almenys un dels dos estigui seleccionat, i a la vegada que hi hagi algun email a enviar.).  
- [x] Els usuaris que no tinguin activada la recepció de newsletters sempre quedaran descartats dels enviaments.

Coses a tenir en compte a posterior només per GENCAT. 
Sobreescriure les capçaleres de la newsletter perquè siguin iguals a les de gencat

- Pas 1. L'admin i l'admin de departament i el procés crearan el Butlletí com fins ara. 
- Pas 2. Un cop guardada la newsletter, podràn:
    -  enviar el Butlletí a tots els que tenen rebre Newsletters, seleccionant el checkbox "Enviar a tots els participants" al clicar-lo s'amagaran els multiselect de cada tipus d'espai i d'interes.
    -  podràn enviar Newsletters als seguidors d'un procés i en un Interés en concret. Els sortirà la següent pantalla per seleccionar els espais participatius i els interessesos.
    - Es distingiran els processos oberts dels tancats (passats) per color o similar. 
    - Els oberts al principi i els tancats al sota, els que estan en draft no apareixen. Ordenar per data si és fàcil si no ho descartem.

   - Hi haurà un select per cada un dels Espais Participatius agrupats per tipus d'espais. 
   - Cada tipus d'Espai tindrà un select amb l'opció TOTS per poder fer: tots els processos, o bé totes les assemblees.

    - Filtre per espai i filtre per interessos es combinen amb AND o OR?
Interessa que es combinin per AND perquè l'OR és el mateix que seleccionar només per interès.

- Pas 3. Enviament de la newsletter

## Screenshots

![screenshot-docs google com-2019 03 25-12-14-33](https://user-images.githubusercontent.com/28536082/54915528-9f6b2a80-4ef7-11e9-9101-bc4c02e1ae9c.png)

**Comment by isaacmg410** [comment]
@tramuntanal This EPIC can be closed, as is already deployed to preprod, right?

**Comment by tramuntanal** [comment]
Right!
