### ISSUE TITLE
[EPIC] Departament Admin

### ISSUE THREAD

**Issue by tramuntanal** [gencat/participa#51]
*(previously titled: "Rols dinàmics: Admin de departament")*

## Is your feature request related to a problem? Please describe.
Actualment quan un departament vol crear un nou procés participatiu, és responsabilitat de l’administrador de la plataforma crear el procés i assignar-hi els administradors de procés que demani el departament.

### Proposta
Per tal de millorar la productivitat tan de l’Administrador de la plataforma com dels Administradors dels processos, es proposa un nou Rol, **l’Administrador de Departament**, que podrà gestionar tots els elements relatius a un departament alhora que podrà crear-ne de nous, sempre lligats a aquell departament.

Seria un nou rol que es pot dir que està entremig del rol Administrador i el rol Administrador de procés:
- **Admin**. L'admin de la plataforma ho pot administrar tot.
- **Admin Departament**. Pot administrar tot el que sigui del seu departament, i crear nous elements sempre associats al seu departament. Mai podrà canviar el departament d’un element que gestioni.
- **Admin d’espai (Procés/Assemblea)**. Només pot administrar un espai en concret. Cal assignar-lo a cada espai on hagi d’aministrar.

### El rol Admin (de la plataforma)
L'Admin ha de poder canviar tan l'assignació del rols “Admin departament”, com canviar-los de departament, perquè el govern pot canviar competències i nom dels departaments (canvi de l'organigrama). És a dir:
- [x] L'admin ha de poder crear Admins de Departament
- [x] L'admin ha de poder canviar el departament al que pertanyen els Admins de Departament https://github.com/gencat/decidim-department-admin/pull/1
- [x] L'admin ha de poder canviar el departament dels processos, normatives, assemblees etc..
Així pot adaptar-se fàcilment als canvis d'organigrama. https://github.com/decidim/decidim/pull/5011

Els departaments/àrees s'hauran de poder crear, editar i modificar.
- [x] _crear_ no té més
- [x] _eliminar_, no permetrà eliminar si hi ha processos o assemblees d'aquell departament. https://github.com/decidim/decidim/pull/5041
- [x] _eliminar_, no permetrà eliminar si hi ha department_users d'aquell departament.
- [x] _modificar_ no té més

### El Rol Admin Departament
Un rol Admin de Departament vindrà definit per:
- [x] necessitarà el permís `allowed_to? :read, :admin_dashboard` per accedir al dashboard d'administrador.
- [x] necessitarà el permís per accedir a l'admin del mòdul ParticipatoryProcesses.
- [x] necessitarà el permís per accedir a l'admin del mòdul Assembiles.
- [x] necessitarà el permís per accedir a l'admin del mòdul Newsletter.
- [x] `decidim_users.admin` estarà marcat a `false` (ja és així). És a dir, no es tractarà com un Admin si no que l'hi anirem donant permisos.
- [x] `decidim_users.roles` inclourà `department_admin`.
- [x] `decidim_users` with role `department_admin` will be related to the area/department via `department_admin_areas` table, a `has_and_belongs_to_many` association.  (Related with #49)

S’indica tot seguit què podrà i què no podrà fer aquest nou rol.

#### Podrà:
- [x] accedir al Tauler d'Administració
- i allà accedir i gestionar segons la seva àrea:
  - [x] accedir i gestionar Processos
  - [x] ha de poder crear processos nous, que automàticament seran del seu departament
  - [x] accedir i gestionar Assemblees
  - [x] ha de poder crear assemblees nous, que automàticament seran del seu departament
  - [x] accedir i gestionar Butlletins
- [x] pot crear nous elements dins dels espais que gestiona.
- [x] Ha de poder gestionar la configuració dels verificadors de cada procés/assemblea

#### NO podrà:
- [x] No pot convidar admins de procés ni d'assemblea (de fet no ha de poder convidar a cap tipus d'admin, per tan l'hi prohibim l'accés a aquesta pantalla).
- [x] Ha de tenir deshabilitada l'edició del departament dels Processos/Consells/normatives… ??
- [x] La newsletter ha de quedar restringida pels participants als processos que l’Admin de Departament  gestiona.

### El Rol Admin de procés (espai)
Aquest rol no es veurà afectat per la creació del nou rol “Admin de departament”.

## Dependencies
- Depends on Department captegorization: #49 
- Depends upon Newsletter: #50

**Comment by tramuntanal** [comment]
I'm going to close this epic ok @agustibr, @aitor and @isaacmg410,
