### ISSUE TITLE
Add Areas to ParticipatoryProcess

### ISSUE THREAD

**Issue by isaacmg410** [gencat/participa#53]
Is part of this issue https://github.com/gencat/participa/issues/49 

## Tasks

- [x] Add Area when copying Assembly
- [x] Add Area when copying Process
- [x] Add Area when creating Process
- [x] Add Area when updating Process
- [x] Add area_id on participatory process form
- [x] Add Area on ParticipatoryProcess Show
- [x] Add relationship between area and process
- [x] Add area on participatory process presenter
- [x] Add locales
- [x] Create migration
- [x] Improve Specs

**Comment by isaacmg410** [comment]
Closed since https://github.com/decidim/decidim/pull/5011 it was merged to master
